sonar.projectKey=akhilkakkireni15_devsecops
sonar.organization=akhilkakkireni15
sonar.sources=.
sonar.host.url=https://sonarcloud.io
sonar.python.coverage.reportPaths=coverage.xml
sonar.login=${SONAR_TOKEN}